#!/usr/bin/env python3.13

import metric_dimension
import re
import signal
import sys
from typing import Any, Callable, cast, List, Optional, Protocol, Tuple
from utils import load_module, parse_args, parse_switch

signal.signal(signal.SIGPIPE, signal.SIG_DFL)

class ProtocolDebug(Protocol):
	debug : Callable[[str, Tuple[Any, ...]], None]
	option_spec : Optional[List[Tuple[List[str], Any, Optional[Callable[[str], Any]]]]]
	option_valid : Optional[Callable[[Tuple[Any, ...]], bool]]
	help : Callable[[], str]

def main(args : List[str]) -> None:
	metric_dimension.__njit_compile__()
	print_help, = cast(
		Tuple[bool],
		parse_args(args[2:], [
			(['-h', '--help'], False, parse_switch)
		])
	)
	if len(args) < 2:
		print(help(), file=sys.stderr)
		return
	graph = args[0]
	module_name = args[1]
	debug = cast(ProtocolDebug, load_module('debug_module.{}'.format(module_name)))
	if print_help:
		print(debug.help(), file=sys.stderr)
		return
	if debug.option_spec is not None:
		debug_option = parse_args(args, debug.option_spec)
		if debug.option_valid is not None and not debug.option_valid(debug_option):
			print(debug.help(), file=sys.stderr)
			return
	else:
		debug_option = cast(Tuple[Any, ...], ())
	debug.debug(graph, debug_option)

def help() -> str:
	return re.sub(r'\n\t\t', r'\n',
	'''
		usage:
			<graph6 string> <debug module>

		options:
			-h, --help
				Prints the module help page.
	'''
	).strip()

if __name__ == '__main__':
	main(sys.argv[1:])
