#!/usr/bin/env python3.13

import metric_dimension
import re
import signal
import sys
from typing import Any, cast, Dict, Iterator, List, Protocol, Tuple
from utils import load_module, parse_args, read_file

signal.signal(signal.SIGPIPE, signal.SIG_DFL)

class ProtocolFormat(Protocol):
	def decode(self, s : str) -> Dict[str, Any]: ...
	def format(self, results : Iterator[str], option_raw : List[str]) -> None: ...

def main(args : List[str]) -> None:
	metric_dimension.__njit_compile__()
	module_name, = cast(
		Tuple[str],
		parse_args(args, [
			(['-m', '--module'], '', None)
		])
	)
	if not module_name:
		print(help(), file=sys.stderr)
		return
	format = cast(ProtocolFormat, load_module('format_module.{}'.format(module_name)))
	results = read_file(sys.stdin)
	format.format(results, args)

def help() -> str:
	return re.sub(r'\n\t\t', r'\n',
	'''
		usage:
			<-m=<format module>>
				Read results from stdin.

		options:
			-m=<module name>, --module=<module name>

			-h, --help
				Prints the module help page.
	'''
	).strip()

if __name__ == '__main__':
	main(sys.argv[1:])
