#!/usr/bin/env python3.13

from functools import partial
import multiprocessing
import metric_dimension
import re
import signal
import sys
from typing import Any, Callable, cast, Dict, List, Optional, Protocol, Tuple
from utils import load_module, parse_args, parse_switch, read_file

signal.signal(signal.SIGPIPE, signal.SIG_DFL)

class ProtocolProcess(Protocol):
	preserve_order : bool
	header : Optional[Callable[[Dict[str, Any]], str]]
	decode : Callable[[str], Dict[str, Any]]
	transform : Callable[[Dict[str, Any], Tuple[Any, ...]], Dict[str, Any]]
	encode : Callable[[Dict[str, Any]], str]
	option_spec : Optional[List[Tuple[List[str], Any, Optional[Callable[[str], Any]]]]]
	option_valid : Optional[Callable[[Tuple[Any, ...]], bool]]
	help : Callable[[], str]

process : Optional[ProtocolProcess] = None

def process_compose(result : str, module_name : str, option : Tuple[Any, ...]) -> Tuple[Dict[str, Any], str]:
	global process
	if process is None:
		process = cast(ProtocolProcess, load_module('process_module.{}'.format(module_name)))
	datum = process.decode(result)
	datum = process.transform(datum, option)
	result = process.encode(datum)
	return datum, result

def main(args : List[str]) -> None:
	metric_dimension.__njit_compile__()
	print_help, module_name = cast(
		Tuple[bool, str],
		parse_args(args, [
			(['-h', '--help'], False, parse_switch),
			(['-m', '--module'], '', None)
		])
	)
	if not module_name:
		print(help(), file=sys.stderr)
		return
	process = cast(ProtocolProcess, load_module('process_module.{}'.format(module_name)))
	if print_help:
		print(process.help(), file=sys.stderr)
		return
	if process.option_spec is not None:
		process_option = parse_args(args, process.option_spec)
		if  process.option_valid is not None and not process.option_valid(process_option):
			print(process.help(), file=sys.stderr)
			return
	else:
		process_option = cast(Tuple[Any, ...], ())
	bound_process_compose = partial(process_compose, module_name=module_name, option=process_option)
	results = read_file(sys.stdin)
	try:
		with multiprocessing.Pool() as pool:
			if process.header is None:
				if process.preserve_order:
					for _, result in pool.imap(bound_process_compose, results):
						print(result)
				else:
					for _, result in pool.imap_unordered(bound_process_compose, results):
						print(result)
			else:
				print_header = True
				if process.preserve_order:
					for datum, result in pool.imap(bound_process_compose, results):
						if print_header:
							print(process.header(datum))
							print_header = False
						print(result)
				else:
					for datum, result in pool.imap_unordered(bound_process_compose, results):
						if print_header:
							print(process.header(datum))
							print_header = False
						print(result)
	except BrokenPipeError:
		return

def help() -> str:
	return re.sub(r'\n\t\t', r'\n',
	'''
		usage:
			<-m=<process module>>
				Read graphs from stdin.

		options:
			-m=<module name>, --module=<module name>

			-h, --help
				Prints the module help page.
	'''
	).strip()

if __name__ == '__main__':
	main(sys.argv[1:])
