#!/usr/bin/env python3.13

from functools import partial
import multiprocessing
import metric_dimension
import re
import signal
import sys
from typing import Any, Callable, cast, Dict, List, Optional, Protocol, Tuple
from utils import load_module, parse_args, parse_switch, read_file

signal.signal(signal.SIGPIPE, signal.SIG_DFL)

class ProtocolProcess(Protocol):
	preserve_order : bool
	header : Optional[Callable[[Dict[str, Any]], str]]
	decode : Callable[[str], Optional[Dict[str, Any]]]
	transform : Callable[[Optional[Dict[str, Any]], Tuple[Any, ...]], Optional[Dict[str, Any]]]
	encode : Callable[[Optional[Dict[str, Any]]], Optional[str]]
	option_spec : Optional[List[Tuple[List[str], Any, Optional[Callable[[str], Any]]]]]
	option_valid : Optional[Callable[[Tuple[Any, ...]], bool]]
	option_augment : Optional[Callable[[Tuple[Any, ...]], Tuple[Any, ...]]]
	help : Callable[[], str]

process : Optional[ProtocolProcess] = None

def process_compose(iresult : str, module_name : str, option : Tuple[Any, ...]) -> Optional[str]:
	global process
	if process is None:
		process = cast(ProtocolProcess, load_module('process_module.{}'.format(module_name)))
	datum = process.decode(iresult)
	datum = process.transform(datum, option)
	oresult = process.encode(datum)
	return oresult

def process_compose_for_header(iresult : str, module_name : str, option : Tuple[Any, ...]) -> Tuple[Optional[Dict[str, Any]], Optional[str]]:
	global process
	if process is None:
		process = cast(ProtocolProcess, load_module('process_module.{}'.format(module_name)))
	datum = process.decode(iresult)
	datum = process.transform(datum, option)
	oresult = process.encode(datum)
	return datum, oresult

def main(args : List[str]) -> None:
	metric_dimension.__njit_compile__()
	print_help, = cast(
		Tuple[bool],
		parse_args(args[1:], [
			(['-h', '--help'], False, parse_switch)
		])
	)
	if len(args) < 1:
		print(help(), file=sys.stderr)
		return
	module_name = args[0]
	process = cast(ProtocolProcess, load_module('process_module.{}'.format(module_name)))
	if print_help:
		print(process.help(), file=sys.stderr)
		return
	if process.option_spec is not None:
		process_option = parse_args(args, process.option_spec)
		if  process.option_valid is not None and not process.option_valid(process_option):
			print(process.help(), file=sys.stderr)
			return
	else:
		process_option = cast(Tuple[Any, ...], ())
	if process.option_augment:
		process_option = process.option_augment(process_option)
	results = read_file(sys.stdin)
	try:
		with multiprocessing.Pool() as pool:
			if process.preserve_order:
				pool_imap = pool.imap
			else:
				pool_imap = pool.imap_unordered
			if process.header is None:
				bound_process_compose = partial(process_compose, module_name=module_name, option=process_option)
				for result in pool_imap(bound_process_compose, results):
					if result:
						print(result)
			else:
				bound_process_compose_for_header = partial(process_compose_for_header, module_name=module_name, option=process_option)
				print_header = True
				for datum, result in pool_imap(bound_process_compose_for_header, results):
					if datum:
						if print_header:
							print(process.header(datum))
							print_header = False
						if result:
							print(result)
	except BrokenPipeError:
		return

def help() -> str:
	return re.sub(r'\n\t\t', r'\n',
	'''
		usage:
			<process module>
				Read graphs from stdin.

		options:
			-h, --help
				Prints the module help page.
	'''
	).strip()

if __name__ == '__main__':
	main(sys.argv[1:])
