#!/usr/bin/env python3.13

from functools import partial
import json
import multiprocessing
import re
import signal
import sys
from typing import Any, cast, Dict, List, Optional, Set, Tuple
from utils import parse_args, parse_switch, read_file

signal.signal(signal.SIGPIPE, signal.SIG_DFL)

def decode(result : str) -> Dict[str, Any]:
	datum = cast(Dict[str, Any], json.loads(result))
	return datum

def extract_graph(result : str) -> str:
	datum = decode(result)
	graph = cast(str, datum['graph'])
	return graph

def remove(result : str, exclude : Set[str]) -> Optional[str]:
	datum = decode(result)
	graph = cast(str, datum['graph'])
	if graph in exclude:
		return None
	return result

def main(args : List[str]) -> None:
	print_help, = cast(
		Tuple[bool],
		parse_args(args[1:], [
			(['-h', '--help'], False, parse_switch)
		])
	)
	if len(args) < 1 or print_help:
		print(help(), file=sys.stderr)
		return
	log_filename = args[0]
	with open(log_filename, 'r') as log_file:
		log_read = read_file(log_file)
		with multiprocessing.Pool() as pool:
			exclude = set(pool.imap_unordered(extract_graph, log_read))
	bind_remove = partial(remove, exclude=exclude)
	results = read_file(sys.stdin)
	try:
		with multiprocessing.Pool() as pool:
			for result in pool.imap_unordered(bind_remove, results):
				if result:
					print(result)
	except BrokenPipeError:
		return

def help() -> str:
	return re.sub(r'\n\t\t', r'\n',
	'''
		usage:
			... <filename>
				Skip graphs that are already within the log file.
	'''
	).strip()

if __name__ == '__main__':
	main(sys.argv[1:])
